trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building Application"

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying Application"

- stage: Verification
  dependsOn: Deploy
  jobs:
  - job: VerifyJob
    steps:
    - script: echo "Verification Successful"